controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_broad:
  ros__parameters:
    use_sim_time: true
    joints:
      - front_left_wheel_joint
      - mid_left_wheel_joint
      - back_left_wheel_joint
      - front_right_wheel_joint
      - mid_right_wheel_joint
      - back_right_wheel_joint
      - camera_pan_joint
      - camera_tilt_joint

diff_cont:
  ros__parameters:
    use_sim_time: true
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true # This is what creates the "odom" frame in RViz

    left_wheel_names: ['front_left_wheel_joint', 'mid_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'mid_right_wheel_joint', 'back_right_wheel_joint']
    
    wheel_separation: 0.23
    wheel_radius: 0.04687

    # This helps with odometry stability
    pose_covariance_diagonal: [0.001, 0.001, 0.01, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.01, 0.01, 0.01, 0.01]

    use_stamped_vel: false